import ThemeSwitchProvider from "@/libs/theme-switch-provider";
import MotionLazy from "@/libs/motion-lazy";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { Toaster } from "sonner";

import "@/app/globals.css";

const inter = Inter({
  variable: "--inter-font",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SumitApp • Website • Design by Sumit Paul",
  description: "Generated by create sumit app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${inter.variable} relative grid min-h-dvh grid-rows-[auto_1fr_auto] overflow-x-hidden antialiased`}>
        <ThemeSwitchProvider>
          <MotionLazy>
            <Header />
            {children}
            <Footer />
            <Toaster />
          </MotionLazy>
        </ThemeSwitchProvider>
      </body>
    </html>
  );
}
